import { theme } from '@/theme';

export const styles = {
  page: {
    minHeight: '100vh',
    backgroundColor: 'var(--bgApp)',
    color: 'var(--textMain)',
    fontFamily: theme.typography.fontSans,
    transition: 'background-color 0.3s ease, color 0.3s ease',
  },
  inner: {
    maxWidth: '1040px',
    margin: '0 auto',
    padding: '40px 28px 120px',
    boxSizing: 'border-box',
  },

  /* Navigation Bar */
  navBar: {
    marginBottom: '24px',
  },
  backLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '13px',
    fontWeight: '600',
    color: 'var(--textMuted)',
    textDecoration: 'none',
    transition: 'color 0.2s',
  },

  /* Studio Header */
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '28px',
    flexWrap: 'wrap',
    gap: '20px',
  },
  headerTitleGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  titleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  title: {
    fontSize: '34px',
    fontWeight: '800',
    color: 'var(--textMain)',
    margin: 0,
    letterSpacing: '-0.03em',
    fontFamily: theme.typography.fontSerif,
    lineHeight: 1.15,
  },
  countBadge: {
    fontSize: '13px',
    fontWeight: '700',
    color: 'var(--textMuted)',
    backgroundColor: 'var(--bgCardHover)',
    border: '1px solid var(--borderDark)',
    padding: '3px 10px',
    borderRadius: '16px',
  },
  subtitle: {
    fontSize: '14px',
    color: 'var(--textMuted)',
    margin: 0,
    lineHeight: '1.5',
    maxWidth: '540px',
  },
  newButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: 'var(--primary)',
    color: '#ffffff',
    padding: '10px 20px',
    borderRadius: '10px',
    fontWeight: '700',
    fontSize: '14px',
    textDecoration: 'none',
    boxShadow: '0 4px 14px rgba(249, 115, 22, 0.3)',
    transition: 'all 0.2s ease',
    border: 'none',
    cursor: 'pointer',
  },

  /* Main Tab Switcher */
  mainTabPillGroup: {
    display: 'flex',
    gap: '8px',
    backgroundColor: 'var(--bgCard)',
    padding: '4px',
    borderRadius: '12px',
    border: '1px solid var(--borderDark)',
    width: 'fit-content',
    marginBottom: '32px',
  },
  mainTabPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 16px',
    borderRadius: '8px',
    border: '1px solid transparent',
    fontSize: '13px',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  pillCountSmall: {
    fontSize: '11px',
    fontWeight: '800',
    backgroundColor: 'var(--bgApp)',
    padding: '2px 6px',
    borderRadius: '8px',
    border: '1px solid var(--borderDark)',
  },

  /* Toolbar */
  toolbar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid var(--borderDark)',
    paddingBottom: '14px',
    marginBottom: '28px',
    flexWrap: 'wrap',
    gap: '16px',
  },
  filterTabs: {
    display: 'flex',
    gap: '24px',
  },
  filterTabBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    background: 'none',
    border: 'none',
    borderBottom: '2px solid transparent',
    padding: '6px 0 14px 0',
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'all 0.2s',
    marginBottom: '-15px',
  },
  filterTabCount: {
    fontSize: '11px',
    fontWeight: '700',
    padding: '2px 7px',
    borderRadius: '10px',
  },
  toolbarRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  searchContainer: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    width: '240px',
  },
  searchIcon: {
    position: 'absolute',
    left: '12px',
    pointerEvents: 'none',
  },
  searchInput: {
    width: '100%',
    padding: '8px 30px 8px 34px',
    borderRadius: '8px',
    border: '1px solid var(--borderDark)',
    backgroundColor: 'var(--bgCard)',
    color: 'var(--textMain)',
    fontSize: '13px',
    outline: 'none',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
  },
  clearBtn: {
    position: 'absolute',
    right: '10px',
    background: 'none',
    border: 'none',
    color: 'var(--textMuted)',
    cursor: 'pointer',
    fontSize: '12px',
  },
  viewToggleGroup: {
    display: 'flex',
    backgroundColor: 'var(--bgCard)',
    border: '1px solid var(--borderDark)',
    borderRadius: '8px',
    padding: '2px',
  },
  viewBtn: {
    background: 'none',
    border: 'none',
    padding: '6px 8px',
    borderRadius: '6px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s',
  },

  /* Editorial List View */
  listView: {
    display: 'flex',
    flexDirection: 'column',
  },
  listRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '32px',
    padding: '24px 0',
    borderBottom: '1px solid var(--borderDark)',
    transition: 'background-color 0.2s',
  },
  listMain: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    minWidth: 0,
  },
  listMetaLine: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
    marginBottom: '2px',
    flexWrap: 'wrap',
  },
  statusDot: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    flexShrink: 0,
  },
  statusText: {
    fontWeight: '700',
    fontSize: '12px',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  metaDot: {
    color: 'var(--textMuted)',
    opacity: 0.5,
  },
  metaTime: {
    color: 'var(--textMuted)',
    fontWeight: '500',
  },
  metaViews: {
    color: 'var(--textMuted)',
    fontWeight: '500',
  },
  listTitleLink: {
    textDecoration: 'none',
    color: 'inherit',
  },
  listTitle: {
    fontSize: '21px',
    fontWeight: '700',
    color: 'var(--textMain)',
    margin: 0,
    lineHeight: '1.3',
    letterSpacing: '-0.015em',
    fontFamily: theme.typography.fontSerif,
  },
  listExcerpt: {
    fontSize: '14px',
    color: 'var(--textMuted)',
    margin: '2px 0 6px 0',
    lineHeight: '1.5',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  listFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: '6px',
    flexWrap: 'wrap',
    gap: '12px',
  },
  slugText: {
    fontFamily: 'monospace',
    fontSize: '12px',
    color: 'var(--textMuted)',
    opacity: 0.7,
  },
  listActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  actionGhostBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '12px',
    fontWeight: '600',
    color: 'var(--textMuted)',
    textDecoration: 'none',
    padding: '5px 10px',
    borderRadius: '6px',
    backgroundColor: 'var(--bgCard)',
    border: '1px solid var(--borderDark)',
    transition: 'all 0.2s',
  },
  actionPillBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    fontSize: '12px',
    fontWeight: '700',
    color: 'var(--textMain)',
    backgroundColor: 'var(--bgCardHover)',
    border: '1px solid var(--borderDark)',
    textDecoration: 'none',
    padding: '5px 12px',
    borderRadius: '6px',
    transition: 'all 0.2s',
    cursor: 'pointer',
  },
  actionDeleteBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '6px 8px',
    borderRadius: '6px',
    border: '1px solid transparent',
    backgroundColor: 'transparent',
    color: 'var(--textMuted)',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  listThumbWrap: {
    width: '130px',
    height: '84px',
    borderRadius: '10px',
    overflow: 'hidden',
    border: '1px solid var(--borderDark)',
    backgroundColor: 'var(--bgCard)',
    flexShrink: 0,
  },
  listThumbImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },

  /* Editorial Grid View */
  gridView: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
    gap: '24px',
  },
  gridCard: {
    backgroundColor: 'var(--bgCard)',
    border: '1px solid var(--borderDark)',
    borderRadius: '16px',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    transition: 'transform 0.2s ease, border-color 0.2s ease',
  },
  gridCoverWrap: {
    width: '100%',
    height: '180px',
    overflow: 'hidden',
    backgroundColor: 'var(--bgApp)',
  },
  gridCoverImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  gridCardBody: {
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
  },
  gridMetaTop: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '12px',
    marginBottom: '8px',
  },
  gridTitleLink: {
    textDecoration: 'none',
    color: 'inherit',
  },
  gridTitle: {
    fontSize: '18px',
    fontWeight: '700',
    color: 'var(--textMain)',
    margin: '0 0 6px 0',
    lineHeight: '1.35',
    fontFamily: theme.typography.fontSerif,
  },
  gridExcerpt: {
    fontSize: '13px',
    color: 'var(--textMuted)',
    lineHeight: '1.5',
    margin: '0 0 16px 0',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  gridFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTop: '1px solid var(--borderDark)',
    paddingTop: '14px',
    marginTop: 'auto',
  },
  gridIconBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '5px 8px',
    borderRadius: '6px',
    backgroundColor: 'var(--bgApp)',
    border: '1px solid var(--borderDark)',
    color: 'var(--textMain)',
    textDecoration: 'none',
    cursor: 'pointer',
  },
  gridDeleteBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '5px 8px',
    borderRadius: '6px',
    border: '1px solid transparent',
    backgroundColor: 'transparent',
    color: '#ef4444',
    cursor: 'pointer',
  },

  /* Collections & Bundles Grid */
  bundlesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(330px, 1fr))',
    gap: '24px',
  },
  bundleCard: {
    backgroundColor: 'var(--bgCard)',
    border: '1px solid var(--borderDark)',
    borderRadius: '18px',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 4px 16px rgba(0,0,0,0.02)',
    transition: 'all 0.25s ease',
  },
  bundleCoverFrame: {
    position: 'relative',
    width: '100%',
    height: '140px',
    backgroundColor: 'var(--bgApp)',
    borderBottom: '1px solid var(--borderDark)',
  },
  bundleCoverImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  bundleCoverFallback: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(135deg, rgba(249, 115, 22, 0.08) 0%, rgba(99, 102, 241, 0.08) 100%)',
  },
  bundleCountChip: {
    position: 'absolute',
    bottom: '10px',
    right: '10px',
    backgroundColor: 'rgba(0,0,0,0.7)',
    color: '#ffffff',
    fontSize: '11px',
    fontWeight: '700',
    padding: '3px 8px',
    borderRadius: '6px',
    backdropFilter: 'blur(6px)',
  },
  bundleCardBody: {
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
  },
  bundleSlugPill: {
    fontSize: '11px',
    fontFamily: 'monospace',
    color: 'var(--primary)',
    marginBottom: '6px',
  },
  bundleTitle: {
    fontSize: '18px',
    fontWeight: '700',
    color: 'var(--textMain)',
    margin: '0 0 6px 0',
    fontFamily: theme.typography.fontSerif,
    lineHeight: '1.3',
  },
  bundleDesc: {
    fontSize: '13px',
    color: 'var(--textMuted)',
    margin: '0 0 16px 0',
    lineHeight: '1.5',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  bundleArticlesList: {
    backgroundColor: 'var(--bgApp)',
    borderRadius: '10px',
    padding: '12px',
    border: '1px solid var(--borderDark)',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    marginBottom: '16px',
  },
  bundleArticlesHeader: {
    fontSize: '10px',
    fontWeight: '800',
    letterSpacing: '0.06em',
    color: 'var(--textMuted)',
    marginBottom: '2px',
  },
  bundleArticleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  bundleOrderBadge: {
    width: '18px',
    height: '18px',
    borderRadius: '50%',
    backgroundColor: 'rgba(249, 115, 22, 0.1)',
    color: 'var(--primary)',
    fontSize: '10px',
    fontWeight: '800',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  bundleArticleTitle: {
    fontSize: '12px',
    fontWeight: '600',
    color: 'var(--textMain)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  moreArticlesNotice: {
    fontSize: '11px',
    color: 'var(--textMuted)',
    fontStyle: 'italic',
    marginTop: '2px',
  },
  bundleFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTop: '1px solid var(--borderDark)',
    paddingTop: '12px',
    marginTop: 'auto',
  },

  /* Empty & Loading States */
  emptyState: {
    padding: '80px 24px',
    textAlign: 'center',
    backgroundColor: 'var(--bgCard)',
    borderRadius: '16px',
    border: '1px dashed var(--borderDark)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  emptyIconWrap: {
    width: '56px',
    height: '56px',
    borderRadius: '16px',
    backgroundColor: 'rgba(249, 115, 22, 0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '14px',
  },
  emptyTitle: {
    fontSize: '18px',
    fontWeight: '700',
    color: 'var(--textMain)',
    margin: '0 0 6px 0',
  },
  emptyText: {
    fontSize: '14px',
    color: 'var(--textMuted)',
    margin: '0 0 20px 0',
    maxWidth: '440px',
    lineHeight: '1.5',
  },
  emptyNewBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: 'var(--primary)',
    color: '#ffffff',
    padding: '9px 18px',
    borderRadius: '8px',
    fontWeight: '700',
    fontSize: '13px',
    textDecoration: 'none',
    border: 'none',
    cursor: 'pointer',
  },
  loadingState: {
    padding: '100px 24px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '12px',
  },
  loadingText: {
    fontSize: '13px',
    color: 'var(--textMuted)',
    fontWeight: '500',
  },

  /* Modal Component */
  modalBackdrop: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    backdropFilter: 'blur(8px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10000,
    padding: '20px',
  },
  modalContent: {
    backgroundColor: 'var(--bgCard)',
    border: '1px solid var(--borderDark)',
    borderRadius: '20px',
    maxWidth: '680px',
    width: '100%',
    maxHeight: '90vh',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 24px 48px -12px rgba(0, 0, 0, 0.25)',
    overflow: 'hidden',
  },
  modalHeader: {
    padding: '24px 28px 20px',
    borderBottom: '1px solid var(--borderDark)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  modalTitle: {
    fontSize: '20px',
    fontWeight: '800',
    color: 'var(--textMain)',
    margin: '0 0 4px 0',
    fontFamily: theme.typography.fontSerif,
  },
  modalSubtitle: {
    fontSize: '13px',
    color: 'var(--textMuted)',
    margin: 0,
  },
  modalCloseBtn: {
    background: 'none',
    border: 'none',
    color: 'var(--textMuted)',
    cursor: 'pointer',
    padding: '4px',
    display: 'flex',
    alignItems: 'center',
  },
  modalBody: {
    padding: '24px 28px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '18px',
  },
  modalInputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  modalRow: {
    display: 'flex',
    gap: '16px',
    flexWrap: 'wrap',
  },
  modalLabel: {
    fontSize: '11px',
    fontWeight: '800',
    letterSpacing: '0.05em',
    color: 'var(--textMuted)',
  },
  modalInput: {
    padding: '10px 14px',
    borderRadius: '10px',
    border: '1px solid var(--borderDark)',
    backgroundColor: 'var(--bgApp)',
    color: 'var(--textMain)',
    fontSize: '13px',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
  },
  modalTextarea: {
    padding: '10px 14px',
    borderRadius: '10px',
    border: '1px solid var(--borderDark)',
    backgroundColor: 'var(--bgApp)',
    color: 'var(--textMain)',
    fontSize: '13px',
    outline: 'none',
    width: '100%',
    minHeight: '70px',
    resize: 'vertical',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
    lineHeight: '1.5',
  },
  articlePickerSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginTop: '4px',
  },
  articlePickerHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '12px',
  },
  modalSearchWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: 'var(--bgApp)',
    border: '1px solid var(--borderDark)',
    borderRadius: '8px',
    padding: '4px 10px',
    width: '180px',
  },
  modalSearchInput: {
    background: 'none',
    border: 'none',
    outline: 'none',
    color: 'var(--textMain)',
    fontSize: '12px',
    width: '100%',
    fontFamily: 'inherit',
  },
  articlesChecklistContainer: {
    maxHeight: '220px',
    overflowY: 'auto',
    border: '1px solid var(--borderDark)',
    borderRadius: '12px',
    padding: '8px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    backgroundColor: 'var(--bgApp)',
  },
  articlePickerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 12px',
    borderRadius: '8px',
    border: '1px solid transparent',
    transition: 'all 0.15s',
  },
  articlePickerLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flex: 1,
    cursor: 'pointer',
    minWidth: 0,
  },
  checkboxInput: {
    accentColor: 'var(--primary)',
    cursor: 'pointer',
    width: '16px',
    height: '16px',
  },
  orderControlsRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    marginLeft: '12px',
  },
  orderPill: {
    fontSize: '11px',
    fontWeight: '800',
    color: 'var(--primary)',
    backgroundColor: 'rgba(249, 115, 22, 0.1)',
    padding: '2px 8px',
    borderRadius: '6px',
    whiteSpace: 'nowrap',
  },
  orderBtn: {
    padding: '4px 6px',
    borderRadius: '4px',
    border: '1px solid var(--borderDark)',
    backgroundColor: 'var(--bgCard)',
    color: 'var(--textMain)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalFooter: {
    padding: '16px 28px',
    borderTop: '1px solid var(--borderDark)',
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    backgroundColor: 'var(--bgCard)',
  },
  modalCancelBtn: {
    padding: '9px 18px',
    borderRadius: '8px',
    border: '1px solid var(--borderDark)',
    backgroundColor: 'transparent',
    color: 'var(--textMain)',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  modalSaveBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '9px 20px',
    borderRadius: '8px',
    border: 'none',
    backgroundColor: 'var(--primary)',
    color: '#ffffff',
    fontSize: '13px',
    fontWeight: '700',
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(249, 115, 22, 0.25)',
  }
};
