import { theme } from '@/theme';

const styles = {
  container: {
    maxWidth: '1280px',
    margin: '0 auto',
    padding: '16px 0 60px',
    fontFamily: theme.typography.fontSans,
    color: 'var(--textMain)',
  },

  /* Header */
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '28px',
    backgroundColor: 'var(--bgCard)',
    padding: '28px 36px',
    borderRadius: '24px',
    border: '1px solid var(--borderDark)',
    boxShadow: '0 20px 40px -15px rgba(0, 0, 0, 0.05)',
    backdropFilter: 'blur(16px)',
    flexWrap: 'wrap',
    gap: '20px',
    transition: 'background-color 0.3s ease, border-color 0.3s ease',
  },
  headerLeft: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  breadcrumbRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '4px',
  },
  systemBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    fontSize: '11px',
    fontWeight: '800',
    color: 'var(--primary)',
    letterSpacing: '0.06em',
  },
  breadcrumbDivider: {
    color: 'var(--textMuted)',
    fontSize: '12px',
  },
  breadcrumbActive: {
    fontSize: '12px',
    fontWeight: '600',
    color: 'var(--textMuted)',
  },
  title: {
    fontSize: '26px',
    fontWeight: '800',
    color: 'var(--textMain)',
    margin: 0,
    fontFamily: theme.typography.fontSerif,
    letterSpacing: '-0.02em',
  },
  subtitle: {
    fontSize: '14px',
    color: 'var(--textMuted)',
    margin: 0,
    fontWeight: '500',
    lineHeight: '1.5',
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    flexWrap: 'wrap',
  },
  liveSiteBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '9px 16px',
    borderRadius: '12px',
    fontSize: '13px',
    fontWeight: '600',
    color: 'var(--textMuted)',
    backgroundColor: 'var(--bgApp)',
    border: '1px solid var(--borderDark)',
    transition: 'all 0.2s ease',
    textDecoration: 'none',
  },
  statusBadgeLive: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: 'var(--statusSuccessBg)',
    color: 'var(--statusSuccess)',
    padding: '9px 18px',
    borderRadius: '12px',
    fontSize: '12px',
    fontWeight: '700',
    border: '1px solid var(--statusSuccessBorder)',
    letterSpacing: '0.04em',
  },
  livePulse: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: 'var(--statusSuccess)',
    boxShadow: '0 0 10px var(--statusSuccess)',
  },
  statusBadgeDraft: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: 'rgba(245, 158, 11, 0.12)',
    color: '#f59e0b',
    padding: '9px 18px',
    borderRadius: '12px',
    fontSize: '12px',
    fontWeight: '700',
    border: '1px solid rgba(245, 158, 11, 0.3)',
    letterSpacing: '0.04em',
  },
  draftPulse: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: '#f59e0b',
  },
  publishBtn: {
    background: 'linear-gradient(135deg, #f97316 0%, #ea580c 100%)',
    color: '#ffffff',
    border: 'none',
    padding: '11px 22px',
    borderRadius: '12px',
    fontWeight: '700',
    fontSize: '14px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    boxShadow: '0 4px 16px rgba(249, 115, 22, 0.35)',
    transition: 'all 0.2s ease',
  },

  /* Alert Message */
  message: {
    padding: '14px 20px',
    borderRadius: '14px',
    border: '1px solid',
    marginBottom: '28px',
    fontSize: '14px',
    fontWeight: '600',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    boxShadow: '0 4px 16px rgba(0,0,0,0.04)',
  },

  /* Vertical Navigation Workspace */
  adminWorkspace: {
    display: 'flex',
    gap: '28px',
    alignItems: 'flex-start',
    width: '100%',
  },
  verticalNavSidebar: {
    width: '260px',
    flexShrink: 0,
    backgroundColor: 'var(--bgCard)',
    borderRadius: '18px',
    border: '1px solid var(--borderDark)',
    padding: '16px 12px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    position: 'sticky',
    top: '24px',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.03)',
  },
  verticalNavGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  navGroupHeader: {
    fontSize: '10.5px',
    fontWeight: '800',
    letterSpacing: '0.08em',
    color: 'var(--textMuted)',
    opacity: 0.65,
    padding: '4px 12px 6px',
    textTransform: 'uppercase',
  },
  verticalTab: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '10px 14px',
    borderRadius: '12px',
    border: '1px solid transparent',
    fontSize: '13px',
    fontWeight: '700',
    textDecoration: 'none',
    cursor: 'pointer',
    position: 'relative',
    transition: 'all 0.2s ease',
  },
  verticalTabIndicator: {
    position: 'absolute',
    left: '4px',
    top: '25%',
    bottom: '25%',
    width: '3px',
    borderRadius: '4px',
    transition: 'background-color 0.2s ease',
  },
  verticalTabLabel: {
    flex: 1,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  verticalNavDivider: {
    height: '1px',
    backgroundColor: 'var(--borderSubtle)',
    margin: '4px 8px',
  },
  verticalContentArea: {
    flex: 1,
    minWidth: 0,
    width: '100%',
  },
  tabCount: {
    fontSize: '11px',
    padding: '2px 7px',
    borderRadius: '10px',
    fontWeight: '800',
    lineHeight: '1.2',
  },
  blogLinkVertical: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 14px',
    backgroundColor: 'transparent',
    color: 'var(--textMain)',
    border: '1px solid transparent',
    borderRadius: '12px',
    fontSize: '13px',
    fontWeight: '700',
    cursor: 'pointer',
    textDecoration: 'none',
    transition: 'all 0.2s ease',
  },

  /* Grid & Sections */
  grid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '40px',
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '18px',
  },
  sectionTitleBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  sectionTitle: {
    fontSize: '18px',
    fontWeight: '800',
    color: 'var(--textMain)',
    margin: 0,
    fontFamily: theme.typography.fontSerif,
    letterSpacing: '-0.01em',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  sectionSubtitle: {
    fontSize: '13px',
    color: 'var(--textMuted)',
    margin: 0,
    lineHeight: '1.4',
  },
  sectionContent: {
    width: '100%',
  },
  bentoGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
    gap: '20px',
  },
  arrayGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(360px, 1fr))',
    gap: '20px',
  },
  arraySectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    flexWrap: 'wrap',
    gap: '12px',
  },

  /* Cards */
  card: {
    backgroundColor: 'var(--bgCard)',
    padding: '24px',
    borderRadius: '20px',
    border: '1px solid var(--borderDark)',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    boxShadow: '0 4px 20px -2px rgba(0, 0, 0, 0.03)',
    transition: 'background-color 0.3s ease, border-color 0.3s ease',
  },
  cardTopRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  categoryPill: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '11px',
    fontWeight: '800',
    color: 'var(--primary)',
    backgroundColor: 'rgba(249, 115, 22, 0.08)',
    padding: '4px 10px',
    borderRadius: '8px',
    letterSpacing: '0.04em',
  },
  itemIndexRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  itemIndexPill: {
    fontSize: '11px',
    fontWeight: '800',
    color: 'var(--textMuted)',
    backgroundColor: 'var(--bgApp)',
    border: '1px solid var(--borderDark)',
    padding: '3px 8px',
    borderRadius: '6px',
  },

  /* Inputs & Labels */
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  inputLabel: {
    fontSize: '11px',
    fontWeight: '700',
    color: 'var(--textMuted)',
    letterSpacing: '0.05em',
  },
  input: {
    padding: '11px 14px',
    borderRadius: '12px',
    border: '1px solid var(--borderDark)',
    fontSize: '14px',
    color: 'var(--textMain)',
    width: '100%',
    fontFamily: theme.typography.fontSans,
    backgroundColor: 'var(--bgApp)',
    transition: 'all 0.2s ease',
    outline: 'none',
    boxSizing: 'border-box',
  },
  textarea: {
    padding: '12px 14px',
    borderRadius: '12px',
    border: '1px solid var(--borderDark)',
    fontSize: '13px',
    lineHeight: '1.6',
    color: 'var(--textMain)',
    width: '100%',
    minHeight: '80px',
    resize: 'vertical',
    fontFamily: theme.typography.fontSans,
    backgroundColor: 'var(--bgApp)',
    transition: 'all 0.2s ease',
    outline: 'none',
    boxSizing: 'border-box',
  },
  imageInputRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    backgroundColor: 'var(--bgApp)',
    padding: '12px',
    borderRadius: '14px',
    border: '1px dashed var(--borderDark)',
  },
  imgPreview: {
    width: '46px',
    height: '46px',
    borderRadius: '10px',
    overflow: 'hidden',
    backgroundColor: 'var(--bgCardHover)',
    border: '1px solid var(--borderDark)',
    flexShrink: 0,
  },
  preview: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  noImgPlaceholder: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '10px',
    color: 'var(--textMuted)',
    fontWeight: '700',
  },

  /* Empty Draft State */
  noDraftCard: {
    padding: '60px 32px',
    backgroundColor: 'var(--bgCard)',
    borderRadius: '24px',
    border: '2px dashed var(--borderDark)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '20px',
    boxShadow: '0 10px 30px rgba(0,0,0,0.02)',
  },
  emptyIconContainer: {
    width: '68px',
    height: '68px',
    borderRadius: '20px',
    backgroundColor: 'rgba(249, 115, 22, 0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  refreshBtnInline: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px 26px',
    backgroundColor: 'var(--textMain)',
    color: 'var(--bgApp)',
    borderRadius: '12px',
    border: 'none',
    fontWeight: '700',
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },

  /* Archives */
  archiveHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: '20px',
  },
  badgePill: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    fontWeight: '700',
    color: 'var(--textMuted)',
    backgroundColor: 'var(--bgCard)',
    padding: '6px 12px',
    borderRadius: '10px',
    border: '1px solid var(--borderDark)',
  },
  archiveGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
    gap: '20px',
  },
  archiveCard: {
    backgroundColor: 'var(--bgCard)',
    padding: '22px',
    borderRadius: '20px',
    border: '1px solid var(--borderDark)',
    cursor: 'pointer',
    transition: 'all 0.25s ease',
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  archiveTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  archiveDate: {
    fontSize: '17px',
    fontWeight: '800',
    color: 'var(--textMain)',
    fontFamily: theme.typography.fontSerif,
  },
  publishedBadge: {
    fontSize: '10px',
    fontWeight: '800',
    color: 'var(--statusSuccess)',
    backgroundColor: 'var(--statusSuccessBg)',
    padding: '4px 8px',
    borderRadius: '6px',
    border: '1px solid var(--statusSuccessBorder)',
    letterSpacing: '0.04em',
  },
  archiveSummary: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    padding: '12px 0',
    borderTop: '1px dashed var(--borderDark)',
    borderBottom: '1px dashed var(--borderDark)',
  },
  summaryItem: {
    fontSize: '13px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  archiveFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '12px',
    color: 'var(--textMuted)',
    fontWeight: '600',
  },
  inspectBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    color: 'var(--primary)',
    fontWeight: '700',
  },

  /* Promo Slider Tab */
  visibilityToggleBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 20px',
    borderRadius: '12px',
    border: '1px solid',
    fontWeight: '800',
    fontSize: '13px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  promoGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
    gap: '24px',
    width: '100%',
  },
  promoCard: {
    backgroundColor: 'var(--bgCard)',
    borderRadius: '20px',
    overflow: 'hidden',
    border: '1px solid var(--borderDark)',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 4px 20px -2px rgba(0, 0, 0, 0.03)',
  },
  promoPreviewWrapper: {
    position: 'relative',
    width: '100%',
    height: '140px',
    backgroundColor: 'var(--bgApp)',
  },
  promoPreview: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    borderBottom: '1px solid var(--borderDark)',
  },
  statusChipFloating: {
    position: 'absolute',
    top: '10px',
    right: '10px',
    color: '#ffffff',
    fontSize: '10px',
    fontWeight: '800',
    padding: '3px 8px',
    borderRadius: '6px',
    letterSpacing: '0.04em',
    backdropFilter: 'blur(8px)',
  },
  promoData: {
    padding: '16px 16px 12px',
  },
  promoActions: {
    padding: '12px 16px',
    display: 'flex',
    gap: '12px',
    backgroundColor: 'var(--bgApp)',
    borderTop: '1px solid var(--borderDark)',
  },
  statusBtn: {
    flex: 1,
    border: '1px solid',
    borderRadius: '10px',
    padding: '8px 12px',
    fontSize: '12px',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  deleteBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '8px 14px',
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    color: '#ef4444',
    border: '1px solid rgba(239, 68, 68, 0.25)',
    borderRadius: '10px',
    fontSize: '12px',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  uploadControls: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  uploadCard: {
    border: '2px dashed var(--borderDark)',
    borderRadius: '20px',
    height: '180px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    backgroundColor: 'var(--bgCard)',
    transition: 'all 0.3s',
  },
  uploadPlaceholder: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '8px',
    textAlign: 'center',
    padding: '16px',
  },
  uploadIconCircle: {
    width: '44px',
    height: '44px',
    borderRadius: '50%',
    backgroundColor: 'rgba(249, 115, 22, 0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '4px',
  },
  urlAddBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    width: '100%',
    padding: '13px',
    backgroundColor: 'var(--bgCard)',
    border: '1px solid var(--borderDark)',
    borderRadius: '14px',
    fontSize: '13px',
    fontWeight: '700',
    color: 'var(--textMain)',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },

  /* Featured Gems Tab */
  sectionHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  addPrimaryBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: 'var(--primary)',
    color: '#ffffff',
    border: 'none',
    padding: '9px 16px',
    borderRadius: '10px',
    fontSize: '13px',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'all 0.2s',
    boxShadow: '0 2px 8px rgba(249, 115, 22, 0.25)',
  },
  gemsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))',
    gap: '20px',
  },
  gemCardTopRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid var(--borderDark)',
    paddingBottom: '12px',
  },
  dragHandle: {
    cursor: 'grab',
    display: 'flex',
    alignItems: 'center',
  },
  gemNumberBadge: {
    fontSize: '11px',
    fontWeight: '800',
    color: 'var(--primary)',
    backgroundColor: 'rgba(249, 115, 22, 0.1)',
    padding: '2px 6px',
    borderRadius: '4px',
  },
  reorderArrowBtn: {
    padding: '4px 6px',
    border: '1px solid var(--borderDark)',
    borderRadius: '6px',
    backgroundColor: 'var(--bgApp)',
    color: 'var(--textMuted)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    lineHeight: 1,
  },
  miniStatusBtn: {
    border: '1px solid',
    borderRadius: '6px',
    padding: '3px 8px',
    fontSize: '11px',
    fontWeight: '700',
    cursor: 'pointer',
  },
  miniDeleteBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '4px 8px',
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    color: '#ef4444',
    border: '1px solid rgba(239, 68, 68, 0.25)',
    borderRadius: '6px',
    cursor: 'pointer',
  },
  gemMediaRow: {
    display: 'flex',
    gap: '12px',
    marginTop: '6px',
    alignItems: 'center',
  },
  gemMediaThumb: {
    width: '68px',
    height: '68px',
    borderRadius: '10px',
    overflow: 'hidden',
    border: '1px solid var(--borderDark)',
    backgroundColor: 'var(--bgApp)',
    flexShrink: 0,
  },
  gemMediaPlaceholder: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'var(--textMuted)',
    fontSize: '10px',
    fontWeight: '700',
  },
  customUploadBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    padding: '7px 12px',
    border: '1px dashed var(--borderDark)',
    borderRadius: '8px',
    fontSize: '11px',
    fontWeight: '700',
    color: 'var(--textMain)',
    backgroundColor: 'var(--bgApp)',
    cursor: 'pointer',
  },
  badgeChoice: {
    width: '42px',
    height: '42px',
    borderRadius: '10px',
    border: '2px solid',
    padding: '5px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s',
  },

  /* Site Settings */
  themeStyleOptionBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 20px',
    borderRadius: '12px',
    border: '2px solid',
    cursor: 'pointer',
    fontSize: '13px',
    transition: 'all 0.2s',
  },
  spotlightPreviewFrame: {
    width: '64px',
    height: '64px',
    borderRadius: '14px',
    overflow: 'hidden',
    boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
    border: '1px solid var(--borderDark)',
    flexShrink: 0,
  },
  cardDivider: {
    height: '1px',
    backgroundColor: 'var(--borderDark)',
    width: '100%',
    margin: '6px 0',
  },
  subHeaderCaps: {
    margin: '0 0 14px 0',
    fontSize: '11px',
    fontWeight: '800',
    color: 'var(--textMuted)',
    letterSpacing: '0.06em',
  },
  historyThumbGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(110px, 1fr))',
    gap: '14px',
  },
  historyThumb: {
    aspectRatio: '1 / 1',
    borderRadius: '12px',
    overflow: 'hidden',
    cursor: 'pointer',
    border: '3px solid',
    transition: 'all 0.2s',
    position: 'relative',
    backgroundColor: 'var(--bgApp)',
  },
  activeCheckBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    backgroundColor: 'var(--primary)',
    borderRadius: '50%',
    width: '18px',
    height: '18px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteFontBtn: {
    backgroundColor: 'transparent',
    border: 'none',
    color: '#ef4444',
    cursor: 'pointer',
    padding: '8px',
    display: 'flex',
    alignItems: 'center',
  },
  saveUrlBtn: {
    padding: '9px 16px',
    backgroundColor: 'var(--textMain)',
    color: 'var(--bgApp)',
    border: 'none',
    borderRadius: '10px',
    fontWeight: '700',
    cursor: 'pointer',
    fontSize: '13px',
    transition: 'all 0.2s',
  },
  uploadNewBtn: {
    padding: '9px 16px',
    backgroundColor: 'var(--primary)',
    color: '#ffffff',
    borderRadius: '10px',
    fontWeight: '700',
    cursor: 'pointer',
    fontSize: '13px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    transition: 'all 0.2s',
  },
  secondaryBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '9px 18px',
    backgroundColor: 'var(--bgApp)',
    color: 'var(--textMain)',
    border: '1px solid var(--borderDark)',
    borderRadius: '10px',
    fontWeight: '700',
    cursor: 'pointer',
    fontSize: '13px',
  },
  primaryActionBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '9px 18px',
    backgroundColor: 'var(--primary)',
    color: '#ffffff',
    border: 'none',
    borderRadius: '10px',
    fontWeight: '700',
    cursor: 'pointer',
    fontSize: '13px',
    boxShadow: '0 2px 8px rgba(249, 115, 22, 0.25)',
  },
  cardBgThumbFrame: {
    width: '56px',
    height: '56px',
    borderRadius: '12px',
    overflow: 'hidden',
    border: '1px solid var(--borderDark)',
    flexShrink: 0,
    backgroundColor: 'var(--bgApp)',
  },

  /* Writers Table */
  tableWrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  tableHeaderRow: {
    display: 'grid',
    gridTemplateColumns: '2fr 2fr 1fr',
    padding: '10px 16px',
    borderBottom: '1px solid var(--borderDark)',
    fontWeight: '800',
    fontSize: '11px',
    color: 'var(--textMuted)',
    letterSpacing: '0.06em',
  },
  tableRow: {
    display: 'grid',
    gridTemplateColumns: '2fr 2fr 1fr',
    alignItems: 'center',
    padding: '14px 16px',
    borderRadius: '14px',
    border: '1px solid var(--borderDark)',
    backgroundColor: 'var(--bgApp)',
    fontSize: '14px',
    gap: '12px',
  },
  userAvatarInitials: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    backgroundColor: 'rgba(249, 115, 22, 0.12)',
    color: 'var(--primary)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: '800',
    fontSize: '14px',
    flexShrink: 0,
  },
  requestedBadge: {
    fontSize: '10px',
    fontWeight: '800',
    backgroundColor: 'rgba(245, 158, 11, 0.15)',
    color: '#f59e0b',
    padding: '2px 6px',
    borderRadius: '4px',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
    display: 'inline-block',
    marginTop: '2px',
  },
  monoIdText: {
    fontFamily: 'monospace',
    fontSize: '12px',
    color: 'var(--textMuted)',
    wordBreak: 'break-all',
  },
  actionAccessBtn: {
    padding: '7px 14px',
    borderRadius: '8px',
    border: '1px solid',
    fontWeight: '700',
    fontSize: '12px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },

  /* Marketing & Logs */
  codeHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  codeTextarea: {
    width: '100%',
    minHeight: '130px',
    padding: '14px',
    borderRadius: '12px',
    border: '1px solid var(--borderDark)',
    fontSize: '13px',
    fontFamily: 'monospace',
    outline: 'none',
    resize: 'vertical',
    backgroundColor: 'var(--bgApp)',
    color: 'var(--textMain)',
    lineHeight: '1.5',
    boxSizing: 'border-box',
  },
  clearLogsBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '7px 14px',
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    color: '#ef4444',
    border: '1px solid rgba(239, 68, 68, 0.25)',
    borderRadius: '8px',
    fontWeight: '700',
    cursor: 'pointer',
    fontSize: '12px',
  },
  terminalContainer: {
    maxHeight: '420px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    paddingRight: '6px',
  },
  terminalLogRow: {
    padding: '12px 14px',
    borderRadius: '10px',
    border: '1px solid var(--borderDark)',
    backgroundColor: 'var(--bgApp)',
    fontSize: '13px',
    color: 'var(--textMain)',
  },
  eventChip: {
    fontWeight: '800',
    color: 'var(--primary)',
    textTransform: 'uppercase',
    fontSize: '11px',
    letterSpacing: '0.04em',
  },
  eventTimestamp: {
    fontSize: '11px',
    color: 'var(--textMuted)',
  },
  eventUrl: {
    color: 'var(--textMuted)',
    fontSize: '12px',
    wordBreak: 'break-all',
    marginTop: '4px',
  },
  metadataCodeBox: {
    marginTop: '6px',
    fontSize: '12px',
    color: 'var(--textMain)',
    fontFamily: 'monospace',
    backgroundColor: 'var(--bgCardHover)',
    padding: '6px 10px',
    borderRadius: '6px',
    border: '1px solid var(--borderDark)',
    overflowX: 'auto',
  },

  /* Auth / Global State */
  stateContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '75vh',
    textAlign: 'center',
    gap: '16px',
    fontFamily: theme.typography.fontSans,
    color: 'var(--textMain)',
  },
  stateTitle: {
    fontSize: '28px',
    fontWeight: '800',
    color: 'var(--textMain)',
    margin: 0,
    fontFamily: theme.typography.fontSerif,
    letterSpacing: '-0.02em',
  },
  stateText: {
    fontSize: '15px',
    color: 'var(--textMuted)',
    maxWidth: '420px',
    lineHeight: '1.6',
    margin: 0,
  },
  backHomeBtn: {
    marginTop: '12px',
    padding: '10px 20px',
    backgroundColor: 'var(--primary)',
    color: '#ffffff',
    borderRadius: '10px',
    fontWeight: '700',
    fontSize: '13px',
    textDecoration: 'none',
  },
  loadingBox: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '10px',
    padding: '36px',
    color: 'var(--textMuted)',
    fontSize: '14px',
    fontWeight: '600',
  },
  emptyMessageBox: {
    textAlign: 'center',
    padding: '36px',
    color: 'var(--textMuted)',
    backgroundColor: 'var(--bgCard)',
    borderRadius: '16px',
    border: '2px dashed var(--borderDark)',
    fontSize: '13px',
    fontWeight: '500',
  },
  emptySmallBox: {
    padding: '24px',
    textAlign: 'center',
    backgroundColor: 'var(--bgApp)',
    borderRadius: '12px',
    color: 'var(--textMuted)',
    fontSize: '12px',
    border: '1px dashed var(--borderDark)',
  }
};

export default styles;
